/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbook;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian Martinez
 */
public class CreatePaper extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    String examname;
    String subject;
    String subjectcode;
    String allowgrade;
    String quection;
    String ans01;
    String ans02;
    String ans03;
    String ans04;
    String correctans;
    String quectionNumber;
    
    
    
    public CreatePaper() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("../Resources/img.png")).getImage());
        this.setTitle("Add Book Student");
        setLocationRelativeTo(null);
        
        conn=DBConnect.connect();
        tablelord();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpaper = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cmbexam = new javax.swing.JComboBox();
        txtsubject = new javax.swing.JTextField();
        txtsubcode = new javax.swing.JTextField();
        txtquenumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtque = new javax.swing.JTextArea();
        cmbalgrade = new javax.swing.JComboBox();
        txtans01 = new javax.swing.JTextField();
        txtans02 = new javax.swing.JTextField();
        txtans03 = new javax.swing.JTextField();
        txtans04 = new javax.swing.JTextField();
        txtcorrectans = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(218, 234, 255));

        tblpaper.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblpaper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblpaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpaperMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpaper);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 880, 160));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 100, 30));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 100, 30));

        jButton3.setBackground(new java.awt.Color(217, 217, 0));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 100, 30));

        jButton4.setBackground(new java.awt.Color(0, 255, 0));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Back");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 70, 30));

        jPanel5.setBackground(new java.awt.Color(218, 234, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbexam.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbexam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select the degree...", "Information and Communication Technologies", "Logistics and distribution", "Administration" }));
        jPanel5.add(cmbexam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        txtsubject.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel5.add(txtsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 300, -1));

        txtsubcode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel5.add(txtsubcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 300, -1));

        txtquenumber.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel5.add(txtquenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 300, -1));

        txtque.setColumns(20);
        txtque.setRows(5);
        jScrollPane1.setViewportView(txtque);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 300, 60));

        cmbalgrade.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbalgrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Group...", "25LA121", "25LA141", "25LA161", "25LA181", "25LA221", "25LA241", "25LA261", "25LA281", "25IL121", "25IL141", "25IL161", "25IL181", "25IL221", "25IL241", "25IL261", "25IL281", "25IT121", "25IT141", "25IT161", "25IT181", "25IT221", "25IT241", "25IT261", "25IT281" }));
        jPanel5.add(cmbalgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 250, -1));

        txtans01.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtans01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtans01ActionPerformed(evt);
            }
        });
        jPanel5.add(txtans01, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 250, -1));

        txtans02.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel5.add(txtans02, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 250, -1));

        txtans03.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel5.add(txtans03, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 250, -1));

        txtans04.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel5.add(txtans04, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 250, -1));

        txtcorrectans.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel5.add(txtcorrectans, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 170, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Correct Answer Number");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 150, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Answer 04");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 70, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Answer 03");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 70, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Answer 02");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 70, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Answer 01");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 70, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Allow Group");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Degree");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 125, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name od the book");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Unit");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 125, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Quection Number");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 125, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Quection");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 125, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 880, 210));

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Playing in English");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/IMAGECHI.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LogOut");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void getData()
    {
    
     examname = cmbexam.getSelectedItem().toString();
     subject = txtsubject.getText();
     subjectcode = txtsubcode.getText();
     allowgrade = cmbalgrade.getSelectedItem().toString();
     quection = txtque.getText();
     ans01 =txtans01.getText();
     ans02 = txtans02.getText();
     ans03 = txtans03.getText();
     ans04 = txtans04.getText();
     correctans = txtcorrectans.getText();
     quectionNumber = txtquenumber.getText();
     
    }
    
    private void clear()
    {
    
     cmbexam.setSelectedIndex(0);
     txtsubject.setText("");
     txtsubcode.setText("");
     cmbalgrade.setSelectedIndex(0);
     txtque.setText("");
     txtans01.setText("");
     txtans02.setText("");
     txtans03.setText("");
     txtans04.setText("");
     txtcorrectans.setText("");
     txtquenumber.setText("");
     
     
    }
     private void tablelord()
    {
        try {
            String sql="SELECT `exam` as 'Degree', `subject` as 'Name Book', `subcode` as 'Unit', `grade` as 'Group',queNumber as 'Question Number', `que` as 'Question', `ans01` as 'Answer 01', `ans02` as 'Answer 02', `ans03` as 'Answer 03', `ans04` as 'Answer 04', `correctans` as 'Correct Answer' FROM `setPaper` ORDER BY subcode ASC , queNumber ASC;";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblpaper.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
          
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
     //  theader();
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getData();
         try {
                String q= "INSERT INTO `setPaper`(`exam`, `subject`, `subcode`, `grade`,queNumber, `que`, `ans01`, `ans02`, `ans03`, `ans04`, `correctans`) VALUES ('"+examname+"', '"+subject+"','"+subjectcode+"','"+allowgrade+"','"+quectionNumber+"','"+quection+"','"+ans01+"','"+ans02+"','"+ans03+"','"+ans04+"','"+correctans+"')";               
                pst=conn.prepareStatement(q);                
                pst.execute(); 
                tablelord();
                clear();
                 JOptionPane.showMessageDialog(rootPane,"Successfully Added");
                    } 
                catch (Exception e) 
                {
                JOptionPane.showMessageDialog(rootPane,e);
                } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtans01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtans01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtans01ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       getData();
        try {
              String squpdate = "UPDATE `setPaper` SET `exam`='"+examname+"',`subject`='"+subject+"',`subcode`='"+subjectcode+"',`grade`='"+allowgrade+"',`que`='"+quection+"',`ans01`='"+ans01+"',`ans02`='"+ans02+"',`ans03`='"+ans03+"',`ans04`='"+ans04+"',`correctans`='"+correctans+"' WHERE queNumber = '"+quectionNumber+"'";
              pst=conn.prepareStatement(squpdate);
                pst.execute();  
                tablelord();
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);              
            }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to delete");
        if(x==0)
        {
            if(quectionNumber.length()>0)
            {
        try {
           
                String sql="DELETE FROM `setPaper` WHERE queNumber='"+ quectionNumber +"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
                tablelord();
                clear();
           JOptionPane.showMessageDialog(rootPane, "sccessfully Delete");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Select Student to Delete");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblpaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpaperMouseClicked
        
        DefaultTableModel tmodel=(DefaultTableModel)tblpaper.getModel();
        int selectrowindex=tblpaper.getSelectedRow();
        cmbexam.setSelectedItem((tmodel.getValueAt(selectrowindex, 0).toString()));
        txtsubject.setText(tmodel.getValueAt(selectrowindex, 1).toString());
         txtsubcode.setText(tmodel.getValueAt(selectrowindex, 2).toString());
         cmbalgrade.setSelectedItem((tmodel.getValueAt(selectrowindex, 3).toString()));
         quectionNumber = (tmodel.getValueAt(selectrowindex, 4).toString());
         txtquenumber.setText(tmodel.getValueAt(selectrowindex, 4).toString());
         txtque.setText(tmodel.getValueAt(selectrowindex, 5).toString());
         txtans01.setText(tmodel.getValueAt(selectrowindex, 6).toString());
         txtans02.setText(tmodel.getValueAt(selectrowindex, 7).toString());
         txtans03.setText(tmodel.getValueAt(selectrowindex, 8).toString());
         txtans04.setText(tmodel.getValueAt(selectrowindex, 9).toString());
         txtcorrectans.setText(tmodel.getValueAt(selectrowindex, 10).toString());
        
        
        
    }//GEN-LAST:event_tblpaperMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked

        this.dispose();

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        int respuesta=JOptionPane.showConfirmDialog(null, "You are sure you want to exit the application?","Mensaje",JOptionPane.OK_CANCEL_OPTION);;
        if(respuesta == 0){
            Login_1 Login_1=new Login_1(); //ventana admin
            Login_1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbalgrade;
    private javax.swing.JComboBox cmbexam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblpaper;
    private javax.swing.JTextField txtans01;
    private javax.swing.JTextField txtans02;
    private javax.swing.JTextField txtans03;
    private javax.swing.JTextField txtans04;
    private javax.swing.JTextField txtcorrectans;
    private javax.swing.JTextArea txtque;
    private javax.swing.JTextField txtquenumber;
    private javax.swing.JTextField txtsubcode;
    private javax.swing.JTextField txtsubject;
    // End of variables declaration//GEN-END:variables
}
