/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbook;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Martinez
 */
public class Paper extends javax.swing.JFrame {

    /**
     * Creates new form Paper
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    int queNo=0;
    int trueAns = 0;
    int falseAns = 0;
    String subname;
    String subcode;
    String exam;
    String regNum;
    String ansnum = "0";
    String correctAns="";
    
    public Paper() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("../Resources/img.png")).getImage());
        this.setTitle("Answer the Questions");
        setLocationRelativeTo(null);
        
        conn=DBConnect.connect();
        loadQue();
        lblregisternum.setText(Login_1.registerNumber);
        lblgrade.setText(Login_1.grade);
        panelord();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblsubcode = new javax.swing.JLabel();
        lblexamname = new javax.swing.JLabel();
        lblregisternum = new javax.swing.JLabel();
        lblgrade = new javax.swing.JLabel();
        lblquection = new javax.swing.JLabel();
        rbtans01 = new javax.swing.JRadioButton();
        rbtans02 = new javax.swing.JRadioButton();
        rbtans03 = new javax.swing.JRadioButton();
        rbtans04 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblanswer = new javax.swing.JTable();
        lblqueNum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblquenumbers = new javax.swing.JLabel();
        lblmark = new javax.swing.JLabel();
        lblcorrectans = new javax.swing.JLabel();
        lblfalseans = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel5.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsubcode.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblsubcode.setForeground(new java.awt.Color(0, 186, 131));
        lblsubcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsubcode.setText("Exam Code");
        jPanel1.add(lblsubcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, -1));

        lblexamname.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblexamname.setForeground(new java.awt.Color(0, 186, 131));
        lblexamname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexamname.setText("Exam Name");
        jPanel1.add(lblexamname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        lblregisternum.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblregisternum.setForeground(new java.awt.Color(0, 186, 131));
        lblregisternum.setText("Register Number");
        jPanel1.add(lblregisternum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        lblgrade.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblgrade.setForeground(new java.awt.Color(0, 186, 131));
        lblgrade.setText("Grade");
        jPanel1.add(lblgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        lblquection.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblquection.setText("Question");
        jPanel1.add(lblquection, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        buttonGroup1.add(rbtans01);
        rbtans01.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rbtans01.setText("Answer 01");
        jPanel1.add(rbtans01, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        buttonGroup1.add(rbtans02);
        rbtans02.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rbtans02.setText("Answer 02");
        jPanel1.add(rbtans02, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        buttonGroup1.add(rbtans03);
        rbtans03.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rbtans03.setText("Answer 03");
        jPanel1.add(rbtans03, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        buttonGroup1.add(rbtans04);
        rbtans04.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rbtans04.setText("Answer 04");
        jPanel1.add(rbtans04, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 140, 30));

        tblanswer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblanswer);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 660, 170));

        lblqueNum.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblqueNum.setText("00");
        jPanel1.add(lblqueNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Group");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Enrollment");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Your answers");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jPanel5.add(jPanel1, "card2");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(215, 215, 215));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Finished Unit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 776, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 3, 24)); // NOI18N
        jLabel2.setText("N. of Questions");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 217, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 3, 24)); // NOI18N
        jLabel5.setText("Correct Answers");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 217, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 3, 24)); // NOI18N
        jLabel6.setText("False Answers");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 217, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 3, 24)); // NOI18N
        jLabel7.setText("Average");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 217, -1, -1));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 458, 154, 41));

        lblquenumbers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblquenumbers.setForeground(new java.awt.Color(51, 255, 51));
        lblquenumbers.setText("Quections");
        jPanel3.add(lblquenumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        lblmark.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmark.setForeground(new java.awt.Color(51, 255, 51));
        lblmark.setText("Mark");
        jPanel3.add(lblmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 280, -1, -1));

        lblcorrectans.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcorrectans.setForeground(new java.awt.Color(51, 255, 51));
        lblcorrectans.setText("Correct");
        jPanel3.add(lblcorrectans, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        lblfalseans.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblfalseans.setForeground(new java.awt.Color(51, 255, 51));
        lblfalseans.setText("false");
        jPanel3.add(lblfalseans, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jPanel5.add(jPanel3, "card3");

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Playing in English");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/IMAGECHI.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LogOut");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//       int xx = Integer.parseInt(ansnum);
//       if(xx>0)
//       {
        getData();
         try {
                String q= "INSERT INTO `answer`(`exam`, `subname`, `subcode`, `registernum`, `quenum`, `answer`) VALUES ('"+exam+"', '"+subname+"','"+subcode+"','"+Login_1.registerNumber+"','"+queNo+"','"+ansnum+"')";               
                pst=conn.prepareStatement(q);                
                pst.execute(); 
              //  tablelord();
               
                 JOptionPane.showMessageDialog(rootPane,"Successfully Recorded");
                    } 
                catch (Exception e) 
                {
                JOptionPane.showMessageDialog(rootPane,e);
                } 
                                if(correctAns.equals(ansnum))
                           {
                               trueAns = trueAns+1;
                           }
                           else
                           {
                               falseAns = falseAns+1;
                           }
        
        int x = Integer.parseInt(lblqueNum.getText());
        if(x==52)
        {
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(jPanel3);
        jPanel5.repaint();
        jPanel5.revalidate(); 
        finish();
        
        }
        else{
        loadQue();
        }
        
//       }
//       else
//       {
//           JOptionPane.showMessageDialog(rootPane, "Select Answer");
//       }
        tablelord();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        try {
             String q= "INSERT INTO `mark`(`subcode`, `regnum`, `totalque`, `correctans`, `falseans`, `avgmark`) VALUES ('"+ExamLogin.correctPaper+"', '"+Login_1.registerNumber+"','"+lblqueNum.getText()+"','"+lblcorrectans.getText()+"','"+lblfalseans.getText()+"','"+lblmark.getText()+"')";               
                pst=conn.prepareStatement(q);                
                pst.execute(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
       
        Home ho= new Home();
        ho.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        int respuesta=JOptionPane.showConfirmDialog(null, "You are sure you want to exit the application?","Mensaje",JOptionPane.OK_CANCEL_OPTION);;
        if(respuesta == 0){
            Login_1 Login_1=new Login_1(); //ventana admin
            Login_1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void finish()
    {
    
    lblquenumbers.setText(queNo+"");
    lblcorrectans.setText(trueAns+"");
    lblfalseans.setText(falseAns+"");
    
    Double tans= Double.valueOf(trueAns);
    Double marks = (tans/52) * 100;
    lblmark.setText(marks+"%");
    
    
    
    
    }
    
     private void tablelord()
    {
        try {
            String sql="SELECT `exam` as 'Degree', `subname` as 'Name od the book', `subcode` as 'Unit', `registernum` as 'Enrollment', `quenum` as 'Quection Number', `answer` as 'Answer' FROM `answer` WHERE subcode = '"+ExamLogin.correctPaper+"' and registernum = '"+Login_1.registerNumber+"' ORDER BY subcode ASC , quenum ASC ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblanswer.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
           
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
     //  theader();
    }
    
    private void panelord()
    {
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(jPanel1);
        jPanel5.repaint();
        jPanel5.revalidate();
    
    }
    
    private void getData()
    {
    
        exam = lblexamname.getText();
        if(rbtans01.isSelected())
        {
            ansnum = "1";
        }
        else if(rbtans02.isSelected())
        {
            ansnum = "2";
        }
        else if(rbtans03.isSelected())
        {
            ansnum = "3";
        }
        else if(rbtans04.isSelected())
        {
            ansnum = "4";
        }
        
    }
    
    private void loadQue()
    {
    
        queNo = queNo+1;
         try {
            String sql="SELECT `exam`, `subject`, `subcode`, `grade`, `queNumber`, `que`, `ans01`, `ans02`, `ans03`, `ans04`, `correctans` FROM `setpaper` where queNumber='"+queNo+"' and subcode = '"+ExamLogin.correctPaper+"' ORDER BY subcode ASC , queNumber ASC;";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
           
               lblexamname.setText(rs.getString("exam"));
               subname=(rs.getString("subject"));
               subcode=(rs.getString("subcode"));
               lblsubcode.setText(subname + "-" + subcode);
               lblqueNum.setText(rs.getString("queNumber"));
               lblquection.setText(rs.getString("que"));
               rbtans01.setText(rs.getString("ans01"));
               rbtans02.setText(rs.getString("ans02"));
               rbtans03.setText(rs.getString("ans03"));
               rbtans04.setText(rs.getString("ans04"));
               correctAns = rs.getString("correctans");
           
           }
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcorrectans;
    private javax.swing.JLabel lblexamname;
    private javax.swing.JLabel lblfalseans;
    private javax.swing.JLabel lblgrade;
    private javax.swing.JLabel lblmark;
    private javax.swing.JLabel lblqueNum;
    private javax.swing.JLabel lblquection;
    private javax.swing.JLabel lblquenumbers;
    private javax.swing.JLabel lblregisternum;
    private javax.swing.JLabel lblsubcode;
    private javax.swing.JRadioButton rbtans01;
    private javax.swing.JRadioButton rbtans02;
    private javax.swing.JRadioButton rbtans03;
    private javax.swing.JRadioButton rbtans04;
    private javax.swing.JTable tblanswer;
    // End of variables declaration//GEN-END:variables
}
